apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGateway
metadata:
  name: gateway-where-for-dinner
  namespace: my-apps
spec:
  service:
    type: ClusterIP
  api:
    version: 1.0.0
    groupId: where-for-dinner
    serverUrl: http://where-for-dinner.tapfull.tapbkp.cloudfocused.in
  env:
  - name: spring.cloud.gateway.httpclient.connect-timeout
    value: "90"
